# Model parameters
learning_rate: 0.01
batch_size: 32
num_epochs: 100

# Network architecture
hidden_layers: [512, 256, 128]
activation: "relu"
dropout_rate: 0.5

# Training settings
optimizer:
  name: "adam"
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8

# Data settings
data:
  train_path: "data/train"
  val_path: "data/val"
  test_path: "data/test"
  batch_size: 32
  num_workers: 4

# Logging settings
logging:
  log_every_n_steps: 100
  save_every_n_epochs: 1
  tensorboard_dir: "runs/"

# System settings
use_gpu: true
seed: 42
